# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weapon_empty_attribute.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "WeaponAttribute" do
    optional :name, :string, 1
    optional :attack_value, :float, 2
    optional :defense_value, :float, 3
    optional :price, :int32, 4
  end
  add_message "WeaponAttributeDictionary" do
    map :weapons, :string, :message, 1, "WeaponAttribute"
  end
end

WeaponAttribute = Google::Protobuf::DescriptorPool.generated_pool.lookup("WeaponAttribute").msgclass
WeaponAttributeDictionary = Google::Protobuf::DescriptorPool.generated_pool.lookup("WeaponAttributeDictionary").msgclass
